Add support for unencrypted private crypt4gh keys
neicnordic/crypt4gh pull request #121
Opened 2024-02-22 12:35 UTC by pontus

This fixes support for unencrypted private crypt4gh keys. Support essentially existed but due to a logic error wasn't usable (KDF was checked against a list of actual KDFs, not including `none`, which is used for the unencrypted case) and failed if no match was found.

This moves the unencrypted case up a bit and lets the following code be a little simpler, also adds a testcase for an unencrypted key.

2024-02-23 16:37 UTC, blankdots commented
i think we can go with version `1.9.1` as the way i read it it is a bug fix
change version https://github.com/neicnordic/crypt4gh/blob/master/internal/version/version.go#L10

2024-02-23 16:38 UTC, blankdots approved these changes

2024-02-23 16:41 UTC, blankdots requested changes
how about we also add a test for decrypting with unprotected key, just in case

2024-02-27 07:26 UTC, dbampalikis approved these changes
Apart for the test mentioned by Stefan, it looks good. Also tested it with the pipeline

2024-02-27 08:22 UTC, blankdots approved these changes

2024-02-27 08:38 UTC, merged