Fix linter issues
neicnordic/crypt4gh pull request #43
Opened 2022-11-23 08:59 UTC by jbygdell

2022-11-23 09:41 UTC, blankdots approved these changes

2022-11-23 11:06 UTC, teemukataja requested changes
config structs were accidentally changed

2022-11-23 11:06 UTC, teemukataja commented on main.go
> +	switch reencryptOptions.SecretKeyFileName {
```suggestion
	switch encryptOptions.SecretKeyFileName {
```

2022-11-29 07:36 UTC, teemukataja approved these changes

2022-11-29 07:56 UTC, merged